language: go

go:
    - 1.12.x

env:
    matrix:
        - OKARCH=amd64 OSARCH=alpine
        - OKARCH=386 OSARCH=debian
script:
    - GOOS=linux GOARCH=$OKARCH go build -o data-forwarder-$OSARCH main.go
deploy:
    provider: releases
    api_key: "$GITHUB_OAUTH_TOKEN"
    file_glob: true
    file:
        - data-forwarder-$OSARCH
    skip_cleanup: true
    on:
      tags: true
